repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-merge-conflict

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks

-   repo: local
    hooks:
    -   id: git-secrets
        name: git-secrets
        entry: git-secrets --pre_commit_hook
        language: system

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.56.0
        -   eslint-plugin-react@7.33.2
        -   eslint-config-prettier@9.1.0
        -   typescript@5.3.3
        -   "@typescript-eslint/eslint-plugin@6.19.1"
        -   "@typescript-eslint/parser@6.19.1"

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

